#!/usr/bin/perl
use strict;
use warnings;
use lib qw( lib extlib ../lib ../extlib );
use MT;
use MT::Template::IncludeMap;
MT->new;
my @tmpls = MT->model('template')->load({
    type => { not => 'backup' }
});

for my $tmpl ( @tmpls ) {
    print STDERR Encode::encode_utf8( sprintf "Making Include map for %s\n", $tmpl->name );
    MT::Template::IncludeMap->make_map($tmpl);
}
print STDERR Encode::encode_utf8("Done...\n");